//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""dbcb64bb-40a0-46e3-ba98-97dc3fa0d735"",
            ""actions"": [
                {
                    ""name"": ""Tap0"",
                    ""type"": ""Button"",
                    ""id"": ""507cbe5f-b0eb-4574-b3f5-7dc8f5848705"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tap1"",
                    ""type"": ""Button"",
                    ""id"": ""e008c286-c6e7-409f-8313-cdda905e7853"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tap2"",
                    ""type"": ""Button"",
                    ""id"": ""ac258a8a-a4ba-4356-84e4-be51f7c07b42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tap3"",
                    ""type"": ""Button"",
                    ""id"": ""fc59c3ae-09c4-4d2d-a3d4-c0fc94e686d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tap4"",
                    ""type"": ""Button"",
                    ""id"": ""208d7f12-a6d8-4766-99d4-02c25ebda703"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tap5"",
                    ""type"": ""Button"",
                    ""id"": ""25d938cd-db3a-46eb-8823-9a299c016919"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold0"",
                    ""type"": ""Button"",
                    ""id"": ""a708908d-43f2-4167-b9d8-124350686b55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold1"",
                    ""type"": ""Button"",
                    ""id"": ""b8684e54-0020-4add-a554-5365f649305a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold2"",
                    ""type"": ""Button"",
                    ""id"": ""815f1a63-7bf7-444e-baf1-7c563115850b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold3"",
                    ""type"": ""Button"",
                    ""id"": ""c7b6e516-a989-43ee-a417-30aa629aac71"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold4"",
                    ""type"": ""Button"",
                    ""id"": ""e909a935-95ca-4da5-9f89-3551c227cbc0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold5"",
                    ""type"": ""Button"",
                    ""id"": ""da5b2b2b-c5a2-48d4-9efb-6a7c521f711a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up0"",
                    ""type"": ""Button"",
                    ""id"": ""5a5cf024-cc22-4440-9368-8bece931bf61"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up1"",
                    ""type"": ""Button"",
                    ""id"": ""ed1ce176-c13f-4772-8987-a1a85ec9962b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up2"",
                    ""type"": ""Button"",
                    ""id"": ""256a4e8a-4021-436b-8b1d-612ef69ed380"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up3"",
                    ""type"": ""Button"",
                    ""id"": ""ccc358a8-3022-456f-96ef-caf276fb33db"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up4"",
                    ""type"": ""Button"",
                    ""id"": ""9b9a9966-1190-49ee-bb71-357a264f7e11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up5"",
                    ""type"": ""Button"",
                    ""id"": ""c160b419-e62b-4de5-a26f-3cc6dc8451fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BarLeft"",
                    ""type"": ""Value"",
                    ""id"": ""f0fb0685-acf4-4d34-82f4-d9aeaf991bf3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BarRight"",
                    ""type"": ""Value"",
                    ""id"": ""2f3dbc8c-1a6c-48bf-a390-9a6227b8afeb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TapL"",
                    ""type"": ""Button"",
                    ""id"": ""8287bc62-1535-49ad-97db-92e8630eaa5a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TapR"",
                    ""type"": ""Button"",
                    ""id"": ""e13bdbc3-7151-401e-901e-54f27901305c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldL"",
                    ""type"": ""Button"",
                    ""id"": ""ca4af56f-bbad-4121-965a-bd2598749fe4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldR"",
                    ""type"": ""Button"",
                    ""id"": ""9ead50d2-eea3-41bb-a6ac-c4ec6a067092"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpL"",
                    ""type"": ""Button"",
                    ""id"": ""6b99db46-d40b-4529-a29c-beac32981401"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpR"",
                    ""type"": ""Button"",
                    ""id"": ""92e183e8-07e0-4634-a318-a167a83c64fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c3258fd3-79a1-45dc-9f46-ee2790d50204"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7c680ee-afd6-4fc5-8cb5-4b2bff183869"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a2935d5-33eb-41e3-8392-0366dd9558a1"",
                    ""path"": ""<DualShockGamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a33f3f68-9a37-4330-baeb-7c18e3d857d5"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44290d39-c7ab-49fe-afae-52fc7ee4720b"",
                    ""path"": ""<DualShockGamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""434ca1a2-5101-4df4-be4f-e0406fccf62b"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a924c74-ace8-45f8-b41b-84a5ddc8fa0d"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8593695-30eb-47df-9a72-2117cc846946"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25867725-3d0f-40fb-9f1f-c6223bf520b3"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9517b7ee-162f-476c-869d-020dcdab9620"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e37ed24-1ee8-4da7-97c6-b88684bff324"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7e5137a-2f91-4774-8251-7b635abf9f9e"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47f9e2d2-d580-4efa-b7b1-e18f2fff8d22"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95c51dc8-f312-4c73-aec3-636308d03c36"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65aedb6d-3b96-4f9c-a61a-e2940b1b4279"",
                    ""path"": ""<DualShockGamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2513b100-9f6c-428b-9c6c-1f72c7af0f90"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""653cfcf1-9a87-4bf0-a3db-9fe2d5bb6619"",
                    ""path"": ""<DualShockGamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dde7806a-459c-4e26-b935-885e58cb03c5"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9091bc90-232d-4243-a146-63980dc1534c"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a279ba75-551f-40f5-bf97-84f45def0391"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34da62c1-6347-4ed7-b0d4-6ab9627467cb"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""864b3f21-4d3b-48b1-ac8d-e762bda5e5ec"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92f9a391-3612-4ebf-a3f1-b89ad4e8f1a9"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59aeab6e-d372-4cf2-88fc-2189329c6a12"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6e88796-c94d-4735-bae6-6c1516f5e252"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c2806a6-2ac1-49d6-a510-df5b0de5f3d6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cf0ba67-a808-4d1c-8da8-51236c226a86"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eeb487c1-a42f-4839-a622-91f050cd0bbe"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d12448e5-6166-4a48-82a9-782c118f04e9"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6494d92b-a3d9-45ab-a98a-dd77f6918f78"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""907976ef-b55d-4776-8827-a686fe09b8f3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f8627db-84ce-48b6-8b4a-067583813baa"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""554d1d40-4b98-437d-b61f-b7f999551fa3"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8319f302-5c39-4d05-9191-44131b3b30a9"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05a33cda-68ae-4e3a-8481-37ec1f58efc4"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""40bfb67f-0b15-4ee6-a121-6cf8b2ba016d"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60026d4d-82a7-4518-88d6-e372846bec26"",
                    ""path"": ""<DualShockGamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BarLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f76b9298-0dd8-48d8-a745-4f240577528d"",
                    ""path"": ""<DualShockGamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BarRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f4b5418-022c-42f9-a1d7-b00212e7cd7a"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23f132bd-5bc4-4b6a-b8c1-a57e9521238d"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""392400ee-2287-4b6c-84cd-21649c2ad526"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fcb13416-c042-4925-9db0-03de4a562ea8"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91411a07-9ff7-4562-bec8-6f84170a3cf2"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""634a9ebc-52a2-444b-b4d0-2c93ab3ad1cd"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldR"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OutGame"",
            ""id"": ""0f61f13f-5a07-49c3-b9d8-44decde21c3c"",
            ""actions"": [
                {
                    ""name"": ""StartPress"",
                    ""type"": ""Button"",
                    ""id"": ""72388466-f618-4999-927f-c3f759c9513a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartRelease"",
                    ""type"": ""Button"",
                    ""id"": ""62161d04-e645-4d65-85ee-28e210c50101"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Value"",
                    ""id"": ""747b9432-03a4-47ed-a6e1-2a348aa8f251"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StartSong"",
                    ""type"": ""Button"",
                    ""id"": ""ae42323f-9990-4612-ac17-cbde51eec1be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d382e17f-4c31-4bc5-bbc8-895a112ad647"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53527e48-0b8e-4d8c-8cc1-ddfb86aa58aa"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Stick"",
                    ""id"": ""fac36424-77f8-49d6-9fc3-66a0eb175222"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b8f7ae56-d8ec-4750-9cbb-d57b3bff7763"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cfafbe0f-d9a6-4e69-ab64-477dfa679074"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""47b64c0c-bfab-4eb6-a2a1-aefea464eddf"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""52d685ec-358a-4674-9c99-e19d82166871"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""65b84805-c654-4066-8d3b-b702d5772f04"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartSong"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""40bd030c-b70a-4d5f-b114-ab5785c1ea81"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartSong"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""82aadd3e-02d9-46c0-b1b3-52bd859fe019"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartSong"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_Tap0 = m_InGame.FindAction("Tap0", throwIfNotFound: true);
        m_InGame_Tap1 = m_InGame.FindAction("Tap1", throwIfNotFound: true);
        m_InGame_Tap2 = m_InGame.FindAction("Tap2", throwIfNotFound: true);
        m_InGame_Tap3 = m_InGame.FindAction("Tap3", throwIfNotFound: true);
        m_InGame_Tap4 = m_InGame.FindAction("Tap4", throwIfNotFound: true);
        m_InGame_Tap5 = m_InGame.FindAction("Tap5", throwIfNotFound: true);
        m_InGame_Hold0 = m_InGame.FindAction("Hold0", throwIfNotFound: true);
        m_InGame_Hold1 = m_InGame.FindAction("Hold1", throwIfNotFound: true);
        m_InGame_Hold2 = m_InGame.FindAction("Hold2", throwIfNotFound: true);
        m_InGame_Hold3 = m_InGame.FindAction("Hold3", throwIfNotFound: true);
        m_InGame_Hold4 = m_InGame.FindAction("Hold4", throwIfNotFound: true);
        m_InGame_Hold5 = m_InGame.FindAction("Hold5", throwIfNotFound: true);
        m_InGame_Up0 = m_InGame.FindAction("Up0", throwIfNotFound: true);
        m_InGame_Up1 = m_InGame.FindAction("Up1", throwIfNotFound: true);
        m_InGame_Up2 = m_InGame.FindAction("Up2", throwIfNotFound: true);
        m_InGame_Up3 = m_InGame.FindAction("Up3", throwIfNotFound: true);
        m_InGame_Up4 = m_InGame.FindAction("Up4", throwIfNotFound: true);
        m_InGame_Up5 = m_InGame.FindAction("Up5", throwIfNotFound: true);
        m_InGame_BarLeft = m_InGame.FindAction("BarLeft", throwIfNotFound: true);
        m_InGame_BarRight = m_InGame.FindAction("BarRight", throwIfNotFound: true);
        m_InGame_TapL = m_InGame.FindAction("TapL", throwIfNotFound: true);
        m_InGame_TapR = m_InGame.FindAction("TapR", throwIfNotFound: true);
        m_InGame_HoldL = m_InGame.FindAction("HoldL", throwIfNotFound: true);
        m_InGame_HoldR = m_InGame.FindAction("HoldR", throwIfNotFound: true);
        m_InGame_UpL = m_InGame.FindAction("UpL", throwIfNotFound: true);
        m_InGame_UpR = m_InGame.FindAction("UpR", throwIfNotFound: true);
        // OutGame
        m_OutGame = asset.FindActionMap("OutGame", throwIfNotFound: true);
        m_OutGame_StartPress = m_OutGame.FindAction("StartPress", throwIfNotFound: true);
        m_OutGame_StartRelease = m_OutGame.FindAction("StartRelease", throwIfNotFound: true);
        m_OutGame_Select = m_OutGame.FindAction("Select", throwIfNotFound: true);
        m_OutGame_StartSong = m_OutGame.FindAction("StartSong", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_Tap0;
    private readonly InputAction m_InGame_Tap1;
    private readonly InputAction m_InGame_Tap2;
    private readonly InputAction m_InGame_Tap3;
    private readonly InputAction m_InGame_Tap4;
    private readonly InputAction m_InGame_Tap5;
    private readonly InputAction m_InGame_Hold0;
    private readonly InputAction m_InGame_Hold1;
    private readonly InputAction m_InGame_Hold2;
    private readonly InputAction m_InGame_Hold3;
    private readonly InputAction m_InGame_Hold4;
    private readonly InputAction m_InGame_Hold5;
    private readonly InputAction m_InGame_Up0;
    private readonly InputAction m_InGame_Up1;
    private readonly InputAction m_InGame_Up2;
    private readonly InputAction m_InGame_Up3;
    private readonly InputAction m_InGame_Up4;
    private readonly InputAction m_InGame_Up5;
    private readonly InputAction m_InGame_BarLeft;
    private readonly InputAction m_InGame_BarRight;
    private readonly InputAction m_InGame_TapL;
    private readonly InputAction m_InGame_TapR;
    private readonly InputAction m_InGame_HoldL;
    private readonly InputAction m_InGame_HoldR;
    private readonly InputAction m_InGame_UpL;
    private readonly InputAction m_InGame_UpR;
    public struct InGameActions
    {
        private @PlayerInput m_Wrapper;
        public InGameActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Tap0 => m_Wrapper.m_InGame_Tap0;
        public InputAction @Tap1 => m_Wrapper.m_InGame_Tap1;
        public InputAction @Tap2 => m_Wrapper.m_InGame_Tap2;
        public InputAction @Tap3 => m_Wrapper.m_InGame_Tap3;
        public InputAction @Tap4 => m_Wrapper.m_InGame_Tap4;
        public InputAction @Tap5 => m_Wrapper.m_InGame_Tap5;
        public InputAction @Hold0 => m_Wrapper.m_InGame_Hold0;
        public InputAction @Hold1 => m_Wrapper.m_InGame_Hold1;
        public InputAction @Hold2 => m_Wrapper.m_InGame_Hold2;
        public InputAction @Hold3 => m_Wrapper.m_InGame_Hold3;
        public InputAction @Hold4 => m_Wrapper.m_InGame_Hold4;
        public InputAction @Hold5 => m_Wrapper.m_InGame_Hold5;
        public InputAction @Up0 => m_Wrapper.m_InGame_Up0;
        public InputAction @Up1 => m_Wrapper.m_InGame_Up1;
        public InputAction @Up2 => m_Wrapper.m_InGame_Up2;
        public InputAction @Up3 => m_Wrapper.m_InGame_Up3;
        public InputAction @Up4 => m_Wrapper.m_InGame_Up4;
        public InputAction @Up5 => m_Wrapper.m_InGame_Up5;
        public InputAction @BarLeft => m_Wrapper.m_InGame_BarLeft;
        public InputAction @BarRight => m_Wrapper.m_InGame_BarRight;
        public InputAction @TapL => m_Wrapper.m_InGame_TapL;
        public InputAction @TapR => m_Wrapper.m_InGame_TapR;
        public InputAction @HoldL => m_Wrapper.m_InGame_HoldL;
        public InputAction @HoldR => m_Wrapper.m_InGame_HoldR;
        public InputAction @UpL => m_Wrapper.m_InGame_UpL;
        public InputAction @UpR => m_Wrapper.m_InGame_UpR;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @Tap0.started += instance.OnTap0;
            @Tap0.performed += instance.OnTap0;
            @Tap0.canceled += instance.OnTap0;
            @Tap1.started += instance.OnTap1;
            @Tap1.performed += instance.OnTap1;
            @Tap1.canceled += instance.OnTap1;
            @Tap2.started += instance.OnTap2;
            @Tap2.performed += instance.OnTap2;
            @Tap2.canceled += instance.OnTap2;
            @Tap3.started += instance.OnTap3;
            @Tap3.performed += instance.OnTap3;
            @Tap3.canceled += instance.OnTap3;
            @Tap4.started += instance.OnTap4;
            @Tap4.performed += instance.OnTap4;
            @Tap4.canceled += instance.OnTap4;
            @Tap5.started += instance.OnTap5;
            @Tap5.performed += instance.OnTap5;
            @Tap5.canceled += instance.OnTap5;
            @Hold0.started += instance.OnHold0;
            @Hold0.performed += instance.OnHold0;
            @Hold0.canceled += instance.OnHold0;
            @Hold1.started += instance.OnHold1;
            @Hold1.performed += instance.OnHold1;
            @Hold1.canceled += instance.OnHold1;
            @Hold2.started += instance.OnHold2;
            @Hold2.performed += instance.OnHold2;
            @Hold2.canceled += instance.OnHold2;
            @Hold3.started += instance.OnHold3;
            @Hold3.performed += instance.OnHold3;
            @Hold3.canceled += instance.OnHold3;
            @Hold4.started += instance.OnHold4;
            @Hold4.performed += instance.OnHold4;
            @Hold4.canceled += instance.OnHold4;
            @Hold5.started += instance.OnHold5;
            @Hold5.performed += instance.OnHold5;
            @Hold5.canceled += instance.OnHold5;
            @Up0.started += instance.OnUp0;
            @Up0.performed += instance.OnUp0;
            @Up0.canceled += instance.OnUp0;
            @Up1.started += instance.OnUp1;
            @Up1.performed += instance.OnUp1;
            @Up1.canceled += instance.OnUp1;
            @Up2.started += instance.OnUp2;
            @Up2.performed += instance.OnUp2;
            @Up2.canceled += instance.OnUp2;
            @Up3.started += instance.OnUp3;
            @Up3.performed += instance.OnUp3;
            @Up3.canceled += instance.OnUp3;
            @Up4.started += instance.OnUp4;
            @Up4.performed += instance.OnUp4;
            @Up4.canceled += instance.OnUp4;
            @Up5.started += instance.OnUp5;
            @Up5.performed += instance.OnUp5;
            @Up5.canceled += instance.OnUp5;
            @BarLeft.started += instance.OnBarLeft;
            @BarLeft.performed += instance.OnBarLeft;
            @BarLeft.canceled += instance.OnBarLeft;
            @BarRight.started += instance.OnBarRight;
            @BarRight.performed += instance.OnBarRight;
            @BarRight.canceled += instance.OnBarRight;
            @TapL.started += instance.OnTapL;
            @TapL.performed += instance.OnTapL;
            @TapL.canceled += instance.OnTapL;
            @TapR.started += instance.OnTapR;
            @TapR.performed += instance.OnTapR;
            @TapR.canceled += instance.OnTapR;
            @HoldL.started += instance.OnHoldL;
            @HoldL.performed += instance.OnHoldL;
            @HoldL.canceled += instance.OnHoldL;
            @HoldR.started += instance.OnHoldR;
            @HoldR.performed += instance.OnHoldR;
            @HoldR.canceled += instance.OnHoldR;
            @UpL.started += instance.OnUpL;
            @UpL.performed += instance.OnUpL;
            @UpL.canceled += instance.OnUpL;
            @UpR.started += instance.OnUpR;
            @UpR.performed += instance.OnUpR;
            @UpR.canceled += instance.OnUpR;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @Tap0.started -= instance.OnTap0;
            @Tap0.performed -= instance.OnTap0;
            @Tap0.canceled -= instance.OnTap0;
            @Tap1.started -= instance.OnTap1;
            @Tap1.performed -= instance.OnTap1;
            @Tap1.canceled -= instance.OnTap1;
            @Tap2.started -= instance.OnTap2;
            @Tap2.performed -= instance.OnTap2;
            @Tap2.canceled -= instance.OnTap2;
            @Tap3.started -= instance.OnTap3;
            @Tap3.performed -= instance.OnTap3;
            @Tap3.canceled -= instance.OnTap3;
            @Tap4.started -= instance.OnTap4;
            @Tap4.performed -= instance.OnTap4;
            @Tap4.canceled -= instance.OnTap4;
            @Tap5.started -= instance.OnTap5;
            @Tap5.performed -= instance.OnTap5;
            @Tap5.canceled -= instance.OnTap5;
            @Hold0.started -= instance.OnHold0;
            @Hold0.performed -= instance.OnHold0;
            @Hold0.canceled -= instance.OnHold0;
            @Hold1.started -= instance.OnHold1;
            @Hold1.performed -= instance.OnHold1;
            @Hold1.canceled -= instance.OnHold1;
            @Hold2.started -= instance.OnHold2;
            @Hold2.performed -= instance.OnHold2;
            @Hold2.canceled -= instance.OnHold2;
            @Hold3.started -= instance.OnHold3;
            @Hold3.performed -= instance.OnHold3;
            @Hold3.canceled -= instance.OnHold3;
            @Hold4.started -= instance.OnHold4;
            @Hold4.performed -= instance.OnHold4;
            @Hold4.canceled -= instance.OnHold4;
            @Hold5.started -= instance.OnHold5;
            @Hold5.performed -= instance.OnHold5;
            @Hold5.canceled -= instance.OnHold5;
            @Up0.started -= instance.OnUp0;
            @Up0.performed -= instance.OnUp0;
            @Up0.canceled -= instance.OnUp0;
            @Up1.started -= instance.OnUp1;
            @Up1.performed -= instance.OnUp1;
            @Up1.canceled -= instance.OnUp1;
            @Up2.started -= instance.OnUp2;
            @Up2.performed -= instance.OnUp2;
            @Up2.canceled -= instance.OnUp2;
            @Up3.started -= instance.OnUp3;
            @Up3.performed -= instance.OnUp3;
            @Up3.canceled -= instance.OnUp3;
            @Up4.started -= instance.OnUp4;
            @Up4.performed -= instance.OnUp4;
            @Up4.canceled -= instance.OnUp4;
            @Up5.started -= instance.OnUp5;
            @Up5.performed -= instance.OnUp5;
            @Up5.canceled -= instance.OnUp5;
            @BarLeft.started -= instance.OnBarLeft;
            @BarLeft.performed -= instance.OnBarLeft;
            @BarLeft.canceled -= instance.OnBarLeft;
            @BarRight.started -= instance.OnBarRight;
            @BarRight.performed -= instance.OnBarRight;
            @BarRight.canceled -= instance.OnBarRight;
            @TapL.started -= instance.OnTapL;
            @TapL.performed -= instance.OnTapL;
            @TapL.canceled -= instance.OnTapL;
            @TapR.started -= instance.OnTapR;
            @TapR.performed -= instance.OnTapR;
            @TapR.canceled -= instance.OnTapR;
            @HoldL.started -= instance.OnHoldL;
            @HoldL.performed -= instance.OnHoldL;
            @HoldL.canceled -= instance.OnHoldL;
            @HoldR.started -= instance.OnHoldR;
            @HoldR.performed -= instance.OnHoldR;
            @HoldR.canceled -= instance.OnHoldR;
            @UpL.started -= instance.OnUpL;
            @UpL.performed -= instance.OnUpL;
            @UpL.canceled -= instance.OnUpL;
            @UpR.started -= instance.OnUpR;
            @UpR.performed -= instance.OnUpR;
            @UpR.canceled -= instance.OnUpR;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);

    // OutGame
    private readonly InputActionMap m_OutGame;
    private List<IOutGameActions> m_OutGameActionsCallbackInterfaces = new List<IOutGameActions>();
    private readonly InputAction m_OutGame_StartPress;
    private readonly InputAction m_OutGame_StartRelease;
    private readonly InputAction m_OutGame_Select;
    private readonly InputAction m_OutGame_StartSong;
    public struct OutGameActions
    {
        private @PlayerInput m_Wrapper;
        public OutGameActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @StartPress => m_Wrapper.m_OutGame_StartPress;
        public InputAction @StartRelease => m_Wrapper.m_OutGame_StartRelease;
        public InputAction @Select => m_Wrapper.m_OutGame_Select;
        public InputAction @StartSong => m_Wrapper.m_OutGame_StartSong;
        public InputActionMap Get() { return m_Wrapper.m_OutGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OutGameActions set) { return set.Get(); }
        public void AddCallbacks(IOutGameActions instance)
        {
            if (instance == null || m_Wrapper.m_OutGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OutGameActionsCallbackInterfaces.Add(instance);
            @StartPress.started += instance.OnStartPress;
            @StartPress.performed += instance.OnStartPress;
            @StartPress.canceled += instance.OnStartPress;
            @StartRelease.started += instance.OnStartRelease;
            @StartRelease.performed += instance.OnStartRelease;
            @StartRelease.canceled += instance.OnStartRelease;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @StartSong.started += instance.OnStartSong;
            @StartSong.performed += instance.OnStartSong;
            @StartSong.canceled += instance.OnStartSong;
        }

        private void UnregisterCallbacks(IOutGameActions instance)
        {
            @StartPress.started -= instance.OnStartPress;
            @StartPress.performed -= instance.OnStartPress;
            @StartPress.canceled -= instance.OnStartPress;
            @StartRelease.started -= instance.OnStartRelease;
            @StartRelease.performed -= instance.OnStartRelease;
            @StartRelease.canceled -= instance.OnStartRelease;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @StartSong.started -= instance.OnStartSong;
            @StartSong.performed -= instance.OnStartSong;
            @StartSong.canceled -= instance.OnStartSong;
        }

        public void RemoveCallbacks(IOutGameActions instance)
        {
            if (m_Wrapper.m_OutGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IOutGameActions instance)
        {
            foreach (var item in m_Wrapper.m_OutGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OutGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public OutGameActions @OutGame => new OutGameActions(this);
    public interface IInGameActions
    {
        void OnTap0(InputAction.CallbackContext context);
        void OnTap1(InputAction.CallbackContext context);
        void OnTap2(InputAction.CallbackContext context);
        void OnTap3(InputAction.CallbackContext context);
        void OnTap4(InputAction.CallbackContext context);
        void OnTap5(InputAction.CallbackContext context);
        void OnHold0(InputAction.CallbackContext context);
        void OnHold1(InputAction.CallbackContext context);
        void OnHold2(InputAction.CallbackContext context);
        void OnHold3(InputAction.CallbackContext context);
        void OnHold4(InputAction.CallbackContext context);
        void OnHold5(InputAction.CallbackContext context);
        void OnUp0(InputAction.CallbackContext context);
        void OnUp1(InputAction.CallbackContext context);
        void OnUp2(InputAction.CallbackContext context);
        void OnUp3(InputAction.CallbackContext context);
        void OnUp4(InputAction.CallbackContext context);
        void OnUp5(InputAction.CallbackContext context);
        void OnBarLeft(InputAction.CallbackContext context);
        void OnBarRight(InputAction.CallbackContext context);
        void OnTapL(InputAction.CallbackContext context);
        void OnTapR(InputAction.CallbackContext context);
        void OnHoldL(InputAction.CallbackContext context);
        void OnHoldR(InputAction.CallbackContext context);
        void OnUpL(InputAction.CallbackContext context);
        void OnUpR(InputAction.CallbackContext context);
    }
    public interface IOutGameActions
    {
        void OnStartPress(InputAction.CallbackContext context);
        void OnStartRelease(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnStartSong(InputAction.CallbackContext context);
    }
}
